Feature/#4 사용자는 식품을 검색한다
towards-sweetly/service-be pull request #5
Opened 2023-07-09 18:43 UTC by youngreal

## 작업에 대한 간단한 요약
#4 음식 검색 

### 변경내역
- 음식 검색
- 음식검색 테스트 

### 어떤부분에 집중해서 리뷰하면좋을지
- properties -> yml로 변경후 DB datasource 작성했는데 push하진않고 로컬에서만 사용중입니다. 
- Food 엔티티는 충돌이 생길수있습니다. 컴파일 에러를 잡기위해 임의로 작성했습니다.

### 이슈번호 첨부,  기타내용
- 커밋 메시지 본문에 최대한 의도를 포함했습니다.

2023-07-10 07:37 UTC, this-is-spear reviewed
`food` 도메인에서 `search` 도메인에 필요한 내용은 `FoodService`라는 `interface`만 필요해보입니다. `FoodServiceImpl`이나 `FoodRepository`와 같은 클래스는 `search` 도메인의 관심사로 보기어렵고 해당 브랜치에서 생성하지 않는게 제가 다른 브랜치에서 `food` 도메인 작업을 진행할 수 있어보입니다.

2023-07-10 07:37 UTC, this-is-spear commented on src/main/java/com/management/servicebe/food/application/FoodServiceImpl.java
> +        }
`searchWord` 가 빈 리스트일 때 빈 리스트를 반환하는건 `search` 패키지에서 검증하는건 어떨까요? `food` 패키지는 `food` 와 관련된 로직만 집중할 수 있도록 관심사를 최대한 분리하는게 좋아 보입니다 ☺️

2023-07-10 07:37 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@PageableDefault(size = 10) Pageable pageable
검색해서 나올 데이터가 10개 이상이 나올 수 있을까 미지수인데, MVP 모델에서는 `Pageable` 인자를 제거하고 필요성을 느낄 때 추가하는건 어떨까요?

2023-07-10 07:37 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +		//todo 페이지 정보(현황) 추가될 수 있다.
해당 주석은 제거해도 될 듯 합니다. 필요하다면 다른 곳에 관리할 수 있는 툴을 정하죠 ☺️

2023-07-10 07:37 UTC, this-is-spear commented on src/main/java/com/management/servicebe/food/application/FoodService.java
> +public interface FoodService {
`search` 도메인에서만 사용할 인터페이스이니 연관된 이름으로 변경하는게 좋아보입니다. `SearchingFoodService`와 같은 이름은 어떨까요?

2023-07-10 07:43 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@RequestParam String searchWord,
`searchWord` 보다 `keyword`나 `searchedWord`가 어떨까요?
```suggestion
			@RequestParam String searchedWord,
```

2023-07-10 07:43 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
요청으로 `GET /food` 가 들어온다면 `REST API`에 맞게 `FOOD`에 대한 정보가 응답으로 제공되어야하지만 검색된 정보들이 반환되고 있습니다. `GET /search?keword={keyword}` 이런식은 어떨까요?

2023-07-10 07:43 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
여담이지만, API 버저닝 전략도 미리 고려하면 수정할 범위가 줄어들 듯 해요! 접두사 처럼 앞에 `/v1/**` 이라는 키워드를 붙이는건 어떨까요? ☺️

2023-07-10 07:43 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/application/SearchFoodService.java
> +//todo 해당 클래스의 역할이 단순 위임인게 조금 아쉬운데 나중에 해당 의존을 스킵하던지(SearchController -> FoodService) 유지하던지 한다.
여기 주석도 제거할 필요가 보입니다 ☺️

2023-07-10 07:59 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@PageableDefault(size = 10) Pageable pageable
음 이부분은 사전에 이야기가 덜된부분같아서 생기는 비용같네요

2023-07-10 08:04 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +		//todo 페이지 정보(현황) 추가될 수 있다.
저는 코드 의도는 잘 기록해두진않는데 todo정도는 주석으로 남기는걸 선호하는편이긴합니다,,ㅋㅋㅋ이전에 todo 주석을 전부 이슈로 빼서 관리하려고 했던적 있는것같던데 //todo 주석만 적는것보다 오히려 불편해지더라구요. 

관리 툴같은건 잘몰랐는데 어떻게할지 정해보고 사용해봐도 괜찮을것같습니다

2023-07-10 08:09 UTC, youngreal commented on src/main/java/com/management/servicebe/food/application/FoodService.java
> +public interface FoodService {
serarch/application의 SearchFoodService를 SearchService로 변경하고
해당 인터페이스 이름을 FoodSearchService나 SearchingFoodService로 변경해도 좋을것같습니다.

해당 인터페이스를 search패키지에서 주입할때 된 food패키지에 있는 인터페이스 라는게 좀더 쉽게 보이는 이름이면 더 좋을것같은데 건창님 선택에 맡기겠습니다,,ㅋㅋ

2023-07-10 08:15 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@RequestParam String searchWord,
단순 "검색어" 라는걸 번역했을때 searchWord가 나오더군요 keyword보다는 searchedWord가 나은것같긴한데 저는  searchWord나 searchedWord 중에서는 크게 상관없습니다. searchedWord로 변경할까요?

2023-07-10 08:21 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
저도 /foods와 /search 로 고민했었는데 이부분이 아직도 헷갈리는거같아요 ㅠ
말씀주신것처럼 /foods 로 수정해서 음식들이 제공될수도 있고 /search 도 되게 좋다고 생각하는데 후자의 경우  **uri만보고 어떤걸 검색하는지 알수없을것 같다**는 생각을했었는데 요부분은 어떻게 생각하시나요? 

별 상관없는건데 제가 고민하는걸지도 모릅니다,,ㅠ

2023-07-10 08:24 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
버저닝도 얘기해보고 포맷을 정해서 문서화를해보고 적용해보면 좋을것같은데,, 어떠신가요??

2023-07-10 08:33 UTC, youngreal commented
> food 도메인에서 search 도메인에 필요한 내용은 FoodService라는 interface만 필요해보입니다.
 FoodServiceImpl이나 FoodRepository와 같은 클래스는 search 도메인의 관심사로 보기어렵고 해당 브랜치에서 생성하지 않는게 제가 다른 브랜치에서 food 도메인 작업을 진행할 수 있어보입니다.

댓글주신 요부분에 대해서 궁금한점이있습니다. 
FoodService인터페이스를통해 food패키지로 넘어가면서 food패키지에서만 의존이 생길텐데 제가 어떻게 작업해서 PR하는게 좋았을까요??

SearchRestController -> SearchFoodService -> FoodService 까지만 작업하고 검색에 대한 세부내용은 결국 FoodRepository를 보게될텐데 아예 기능자체를 미완 하더라도 FoodService까지만 작업했었어야했다 일까요?

2023-07-10 10:20 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@PageableDefault(size = 10) Pageable pageable
`offset` 기반말고도 `cursor`도 고려할 수 있을 듯 합니다. 이런 설정 방법은 DB 성능에 맞게 구현해도 늦지 않아 보이는데, 전자로 진행해서 이후 작업을 유연하게 이끌어보죠 ☺️

2023-07-10 10:22 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +		//todo 페이지 정보(현황) 추가될 수 있다.
저희는 Projects에서 대부분 작업이 관리가 되는데 코드 상에서도 관리가 된다면 시간 차이로 인해 혼란이 생길까 우려됩니다. 😿 만약 Issue로 나오지 않는 작업이라면 사용자에게 가치가 전달되지 않는 작업이 될 수 도 있습니다..! 작업의 우선도와 가치를 측정하기 위해 따로 관리하는게 좋아보입니다! 

Projects 에서 추가적인 정보를 어떻게 더 전달할 수 있을지 같이 고민해보죠 ㅎㅎ

2023-07-10 10:24 UTC, this-is-spear commented on src/main/java/com/management/servicebe/food/application/FoodService.java
> +public interface FoodService {
음... 인터페이스가 food 도메인에 위치할 테니 food 도메인을 관리하는 입장에서 쉽게 판별할 수 있게 외부 도메인을 우선적으로 작성하는 게 편리해보입니다.

저는 `SearchingFoodService`가 조금 더 편리하지 않을까 생각드네요 ☺️

2023-07-10 10:25 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +			@RequestParam String searchWord,
오 그렇네요! 말씀하신 것처럼 `searchWord`가 더 의미있군요! 좋습니다 👍

2023-07-10 10:28 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
> 저도 /foods와 /search 로 고민했었는데 이부분이 아직도 헷갈리는거같아요 ㅠ 말씀주신것처럼 /foods 로 수정해서 음식들이 제공될수도 있고 /search 도 되게 좋다고 생각하는데 후자의 경우 **uri만보고 어떤걸 검색하는지 알수없을것 같다**는 생각을했었는데 요부분은 어떻게 생각하시나요?
> 
> 별 상관없는건데 제가 고민하는걸지도 모릅니다,,ㅠ

/foods로 전달하기에는 검색 결과가 반환되니 이후에 API 변경이 많아질 것으로 예상됩니다! `/search`로 할 경우 클라이언트 입장에서는 `검색이 된다`를 이해하고 `검색된 결과를 받아야 한다.` 만 이해해도 충분하지 않을까 생각드네요. 

추가로 만약 클라이언트가 결과를 받고 어떤 행동을 취할지 모르는게 걱정이라면 `HATEOAS`를 활용해 검색 결과를 풍부하게 전달하는건 어떨까요?

2023-07-10 10:29 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
> 버저닝도 얘기해보고 포맷을 정해서 문서화를해보고 적용해보면 좋을것같은데,, 어떠신가요??

어떤 문서가 작성되면 좋을까요? 전 아직 버저닝과 관련된 문서를 작성한 적이 없어서 감이 잡히지 않습니다 😿

2023-07-10 10:32 UTC, this-is-spear commented
> > food 도메인에서 search 도메인에 필요한 내용은 FoodService라는 interface만 필요해보입니다.
> > FoodServiceImpl이나 FoodRepository와 같은 클래스는 search 도메인의 관심사로 보기어렵고 해당 브랜치에서 생성하지 않는게 제가 다른 브랜치에서 food 도메인 작업을 진행할 수 있어보입니다.
> 
> 댓글주신 요부분에 대해서 궁금한점이있습니다. FoodService인터페이스를통해 food패키지로 넘어가면서 food패키지에서만 의존이 생길텐데 제가 어떻게 작업해서 PR하는게 좋았을까요??
> 
> SearchRestController -> SearchFoodService -> FoodService 까지만 작업하고 검색에 대한 세부내용은 결국 FoodRepository를 보게될텐데 아예 기능자체를 미완 하더라도 FoodService까지만 작업했었어야했다 일까요?

결론은 말씀드리면 말씀하신게 맞습니다. 미완성인 채로 머지되는 건 좋은 형태는 아니지만 도메인보다 검색이 먼저 구현되다보니 발생하는 문제처럼 보입니다. 제가 도메인을 구현한 이후에 인터페이스의 구현체를 구현하는 순서가 맞다고 생각듭니다. 그 전에는 프레젠테이션 레이어와 애플리케이션 서비스 레이어만 구현하는 형태로 진행하면 좋겠습니다.

2023-07-10 11:12 UTC, youngreal commented
> 결론은 말씀드리면 말씀하신게 맞습니다. 미완성인 채로 머지되는 건 좋은 형태는 아니지만 도메인보다 검색이 먼저 구현되다보니 발생하는 문제처럼 보입니다. 제가 도메인을 구현한 이후에 인터페이스의 구현체를 구현하는 순서가 맞다고 생각듭니다. 그 전에는 프레젠테이션 레이어와 애플리케이션 서비스 레이어만 구현하는 형태로 진행하면 좋겠습니다.

2023-07-10 11:18 UTC, youngreal commented
>결론은 말씀드리면 말씀하신게 맞습니다. 미완성인 채로 머지되는 건 좋은 형태는 아니지만 도메인보다 검색이 먼저 구현되다보니 발생하는 문제처럼 보입니다. 제가 도메인을 구현한 이후에 인터페이스의 구현체를 구현하는 순서가 맞다고 생각듭니다. 그 전에는 프레젠테이션 레이어와 애플리케이션 서비스 레이어만 구현하는 형태로 진행하면 좋겠습니다.

그러면 다음에 이런경우에는 참조되는쪽(지금의 food)에서 먼저 작업을 끝내고 제가 PR을 올리는게 좋겠군요??
중간작업을 pr해야한다면 말씀주신것처럼 참조가 없도록선에서 pr을하구요.
이해한게 맞을까요?

2023-07-10 11:34 UTC, youngreal commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
> 어떤 문서가 작성되면 좋을까요? 전 아직 버저닝과 관련된 문서를 작성한 적이 없어서 감이 잡히지 않습니다 😿

2023-07-11 11:56 UTC, this-is-spear commented
해당 PR과 `Food` 작업 PR을 머지한 다음 새로운 PR로 진행하는건 어떨까요? 저도 이 부분은 특별하게 뭐가 좋을지 예상은 안가지만 `Food` 관련 작업의 결과를 해당 PR로 병합하는 일은 꽤 신경쓸 일이 많아 보입니다!

2023-07-11 11:58 UTC, this-is-spear commented on src/main/java/com/management/servicebe/search/ui/SearchRestController.java
> +	@GetMapping("/food")
음 API 명세표를 만들기 위해서는 컨벤션이 필요해보이는데, 여기서 정하는건 어떨까요? 저는 클라이언트 측에서 쉽게 판별할 수 있는 접두가 `/v1/**` 방법이 무난해보입니다 ☺️

2023-07-11 11:59 UTC, this-is-spear requested changes
`SearchingFoodServiceImpl`, `Food`, `FoodRepository`는 search 도메인과 연관이 없는 클래스라고 생각됩니다. 삭제하는게 어떨까요?

2023-07-13 00:27 UTC, youngreal commented
일단 전부삭제하긴했는데 이부분은 필요없는 비용이 생긴부분이라고 생각합니다ㅠ 다음엔 개선해보시죠,,

2023-07-13 00:30 UTC, youngreal commented
> 해당 PR과 Food 작업 PR을 머지한 다음 새로운 PR로 진행하는건 어떨까요? 저도 이 부분은 특별하게 뭐가 좋을지 예상은 안가지만 Food 관련 작업의 결과를 해당 PR로 병합하는 일은 꽤 신경쓸 일이 많아 보입니다! 

food관련 작업의 내용을 전부 삭제해서 이제 건창님 작업과 해당 PR 머지 여부랑 상관없을것같습니다. SearchingFoodService 인터페이스 하나이려나요..

2023-07-13 17:18 UTC, this-is-spear approved these changes
수고하셨습니다 ☺️🙇‍♂️
내일 함께 남은 작업에 대해서 함께 이야기해봐요 🙇‍♂️

2023-07-14 11:47 UTC, merged